basePath: /api/v1
definitions:
  request.AuthCreate:
    properties:
      name:
        type: string
      password:
        type: string
      role:
        type: string
      user_type:
        type: string
    type: object
  request.AuthLogin:
    properties:
      id:
        type: integer
      password:
        type: string
    type: object
  request.AuthUpdate:
    properties:
      name:
        type: string
      role:
        type: string
      user_type:
        type: string
    type: object
  request.CompanyCreate:
    properties:
      name:
        type: string
    type: object
  request.CompanyUpdate:
    properties:
      name:
        type: string
    type: object
  request.TaskCreate:
    properties:
      detail:
        type: string
      limit_date:
        type: string
      person_in_charge_id:
        type: integer
      title:
        type: string
      visibility:
        type: string
    type: object
  request.TaskUpdate:
    properties:
      detail:
        type: string
      limit_date:
        type: string
      person_in_charge_id:
        type: integer
      status:
        type: string
      title:
        type: string
      visibility:
        type: string
    type: object
  response.AuthLogin:
    properties:
      companyID:
        type: integer
      token:
        type: string
      userID:
        type: integer
    type: object
  todo_api_internal_adapter_inbound_http_model.Company:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  todo_api_internal_adapter_inbound_http_model.Task:
    properties:
      create_at:
        type: string
      creator:
        $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.User'
      detail:
        type: string
      id:
        type: integer
      limit_date:
        type: string
      person_in_charge:
        $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.User'
      status:
        type: string
      title:
        type: string
      update_at:
        type: string
      updator:
        $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.User'
      visibility:
        type: string
    type: object
  todo_api_internal_adapter_inbound_http_model.User:
    properties:
      company:
        $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.Company'
      id:
        type: integer
      name:
        type: string
      role:
        type: string
      user_type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: TODO API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: ログインを行い、トークンを発行する。
      parameters:
      - description: ログイン用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.AuthLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AuthLogin'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: ログイン
      tags:
      - auth
  /company/{company_id}:
    get:
      consumes:
      - application/json
      description: 企業の情報をIDから取得する。管理会社のユーザのみ実行可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.Company'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: 企業の取得
      tags:
      - company
  /company/{company_id}/task/{task_id}:
    get:
      consumes:
      - application/json
      description: 閲覧可能なタスクの情報をIDから取得する。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: タスクID
        in: path
        name: task_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.Task'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: タスクの取得
      tags:
      - task
  /company/{company_id}/task/{task_id}/status/{task_status}:
    put:
      consumes:
      - application/json
      description: タスクのステータスを指定した状態へと更新する。編集者のみ可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: タスクID
        in: path
        name: task_id
        type: integer
      - description: タスクステータス
        in: path
        name: task_status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: タスクステータスの更新
      tags:
      - task
  /company/{company_id}/task/{task_id}/update:
    put:
      consumes:
      - application/json
      description: タスクの情報を更新する。編集者のみ可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: タスクID
        in: path
        name: task_id
        type: integer
      - description: タスク更新用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.TaskUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: タスクの更新
      tags:
      - task
  /company/{company_id}/task/create:
    post:
      consumes:
      - application/json
      description: タスクを作成する。編集者のみ可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: タスク作成用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.TaskCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: タスクの作成
      tags:
      - task
  /company/{company_id}/task/list:
    get:
      consumes:
      - application/json
      description: 閲覧可能なタスクの一覧を企業IDから取得する。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.Task'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: 企業のタスク一覧の取得
      tags:
      - task
  /company/{company_id}/task/list_by_assigned_user_id/{assigned_user_id}:
    get:
      consumes:
      - application/json
      description: 閲覧可能なタスクの一覧を割り当てユーザIDから取得する。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: ユーザID
        in: path
        name: assigned_user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.Task'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: ユーザに割り当てられたタスク一覧の取得
      tags:
      - task
  /company/{company_id}/update:
    put:
      consumes:
      - application/json
      description: 企業を作成する。管理会社の管理者のみ実行可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: 企業更新用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.CompanyUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: 企業の更新
      tags:
      - company
  /company/{company_id}/user/{user_id}:
    get:
      consumes:
      - application/json
      description: ユーザの情報をIDから取得する。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: ユーザID
        in: path
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todo_api_internal_adapter_inbound_http_model.User'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: ユーザの取得
      tags:
      - user
  /company/{company_id}/user/{user_id}/update:
    post:
      consumes:
      - application/json
      description: ユーザの情報を更新する。管理会社の管理者と企業の管理者に実行可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: ユーザID
        in: path
        name: user_id
        type: integer
      - description: ユーザ更新用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.AuthUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: ユーザの更新
      tags:
      - user
  /company/{company_id}/user/create:
    post:
      consumes:
      - application/json
      description: ユーザを登録する。管理会社の管理者と企業の管理者に実行可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業ID
        in: path
        name: company_id
        type: integer
      - description: ユーザ作成用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.AuthCreate'
      produces:
      - application/json
      responses:
        "200":
          description: 登録されたユーザID
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: ユーザの登録
      tags:
      - user
  /company/create:
    post:
      consumes:
      - application/json
      description: 企業を作成する。管理会社の管理者のみ実行可能。
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 企業作成用リクエスト
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.CompanyCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: 企業の作成
      tags:
      - company
  /healthz:
    get:
      consumes:
      - application/json
      description: ヘルスチェック
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: ヘルスチェック
      tags:
      - root
swagger: "2.0"
